### PR TITLE
Renamed Docuemnt concept to Database, reviewed database.md

### PR DESCRIPTION
**Pull request by root-hal9000**
Issue #32

### CODE REVIEW

**Comment by root-hal9000** [comment]
question: we have renamed all the .md files - do they need to be updated in the meta.json file?

**Comment by rauenzi** [comment]
> question: we have renamed all the .md files - do they need to be updated in the meta.json file?

to make it importable into Trilium _perfectly_ then yes

**Comment by root-hal9000** [comment]
> LGTM 👍

Looks good to merge? I am bad with acronyms 😂

**Comment by root-hal9000** [comment]
> > question: we have renamed all the .md files - do they need to be updated in the meta.json file?
> 
> to make it importable into Trilium _perfectly_ then yes

Ok, I will raise an issue to do that separately then.

**Comment by rauenzi** [comment]
> > LGTM 👍
> 
> Looks good to merge? I am bad with acronyms 😂

LGTM = Looks Good To Me

**Comment by Alumniminium** [comment]
Please don't approve PRs that have merge conflicts lmao :laughing:

**Comment by root-hal9000** [comment]
@meichthys thanks for fixing the merge conflicts - I didn't have time to look at them before leaving. In resolving them, I think you accidentally got those two files back to having links to the old file name (document.md rather than database.md). I made one more commit to fix that, merging now

**Comment by root-hal9000** [comment]
> Sorry about that, I was In a rush today and I shouldn't have tried to tackle it.

nope, same here, should have looked at conflict before requesting review. thank you!

**Pull request merged**
