### PR TITLE
Added section on running with Docker Compose

### PR DESCRIPTION
**Pull request by slashtechno**
Added a section on running with Docker Compose to go along with [triliumnext/Notes#309](https://github.com/TriliumNext/Notes/pull/309)

***

> **Note:** Trilium's Docker container requires root privileges to operate correctly.

Looking at the `Dockerfile`, I don't see why this wouldn't be work in a rootless environment. Can this be removed?

Also, regarding the `Local Access Only` section, from what I can tell, the current instructions do not take different network adapter names or subnets into account. In addition, I imagine most people would have a firewall in place anyway. However, I'm not too familiar with using Docker networks in this fashion so I didn't update it.

### CODE REVIEW

**Comment by rauenzi** [comment]
I know it's pretty common to do but I would hesitate against recommending a full `git clone https://github.com/TriliumNext/Notes.git`. The repository is quite large (183M) and very much overkill when all you're interested in is a single text file.

**Comment by Alumniminium** [comment]
> I know it's pretty common to do but I would hesitate against recommending a full `git clone https://github.com/TriliumNext/Notes.git`. The repository is quite large (183M) and very much overkill when all you're interested in is a single text file.

I'll take care of that momentarily

**Comment by slashtechno** [comment]
@Alumniminium Docker uses the name of the directory that the `docker-compose.yml` is in for naming containers. Should I make a quick PR that adds the `mkdir`and `cd` commands prior to running `wget`?

**Comment by Alumniminium** [comment]
> @Alumniminium Docker uses the name of the directory that the `docker-compose.yml` is in for naming containers. Should I make a quick PR that adds the `mkdir`and `cd` commands prior to running `wget`?

good catch, feel free, otherwise I'll do it tomorrow.

**Pull request merged**
